@echo off
setlocal

REM Delete "out" folder if it exists
if exist "out" (
    echo Deleting folder: out
    rmdir /s /q "out"
)

REM Delete files inside the "ci" folder if they exist
if exist "ci\RemoteSpy.rbxm" (
    echo Deleting ci\RemoteSpy.rbxm
    del /f /q "ci\RemoteSpy.rbxm"
)

if exist "ci\RemoteSpy.dev.lua" (
    echo Deleting ci\RemoteSpy.dev.lua
    del /f /q "ci\RemoteSpy.dev.lua"
)

REM Run npm command
echo Running npm run return ...
npm run return

REM Open RemoteSpy.dev.lua (new one generated by npm command)
if exist "ci\RemoteSpy.dev.lua" (
    echo Opening RemoteSpy.dev.lua...
    start "" "ci\RemoteSpy.dev.lua"
)

endlocal
pause
